apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: most-serious
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: most-serious
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: listshop-configmap
                  key: db.host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: listshop-configmap
                  key: db.port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: listshop-configmap
                  key: db.name
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"
              livenessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 180
              readinessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30